### ISSUE TITLE
Fix Typo in Chapter 7 section 3

### ISSUE THREAD

**Issue by afarnudi** [SPE-R/SPE#13]
The  P -value refers to the test of the null hypothesis that there is no effect of ***shyp*** on birth weight 

to 

The  P -value refers to the test of the null hypothesis that there is no effect of ***hyp*** on birth weight

**Comment by afarnudi** [comment]
I don't have access to create a branch and make a pull request. I will do it if you grant me access.

**Comment by DamienGeorges** [comment]
fixed in [4b9f334](https://github.com/SPE-R/SPE/commit/4b9f33401288eb8f09b9835691ae7497bf88ee43)
